In [19]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [20]:
import numpy as np
import jax.numpy as jnp
import jax
from lm import LM
import scipy as sp
jnp.set_printoptions(precision=4,linewidth=120)


In [21]:
N=100
Nx=20
rng=np.random.default_rng(seed=123)
arr = np.tile(np.arange(N).reshape(N,1),(1,Nx))
offset = rng.permuted(np.tile(np.arange(1,N),(N,1)), axis=1)[:,:Nx-1]
arr[:,1:]+=offset
arr %= N
x = jnp.asarray(rng.uniform(size=N))
a = rng.uniform(size=(N,Nx))
b = jnp.sum(a*x[arr]**2,axis=1)
x0 = x+rng.uniform(-0.01,0.01,size=N)

In [22]:
@jax.jit
def f(x):
    return jnp.sum(a*x[arr]**2,axis=1)-b

In [36]:
solver=LM(f,x0)


In [37]:
res=solver(L=1e7, maxiter=1000, ftol=1e-12,iter_print=5)
res.f

Levenberg-Marquadrt Jacobian shape: (100, 100)
Iteration: 5  L: 1.69e+02
f abs mean: 1.48e-02  max: 6.24e-02
Iteration: 10  L: 2.87e-03
f abs mean: 4.34e-04  max: 2.41e-03
Iteration: 15  L: 4.86e-08
f abs mean: 2.90e-07  max: 9.67e-07
Iteration: 17  L: 6.00e-10
f abs mean: 5.90e-14  max: 1.90e-13


Array([-9.77e-15, -6.22e-15,  2.98e-14,  1.78e-15,  4.62e-14,  1.03e-13,  8.79e-14,  1.43e-13,  5.86e-14, -8.08e-14,
       -6.79e-14,  1.07e-14, -4.00e-14,  7.99e-15, -5.77e-15, -1.15e-14,  3.77e-14,  3.20e-14,  1.42e-14, -7.73e-14,
        8.30e-14, -4.44e-14, -6.35e-14,  7.86e-14, -3.15e-14, -8.08e-14,  8.17e-14,  7.55e-14,  3.55e-14,  5.33e-14,
        4.35e-14,  1.50e-13, -5.77e-14, -4.26e-14,  9.06e-14,  5.20e-14,  1.78e-14, -5.82e-14,  1.38e-14,  6.57e-14,
        2.66e-15, -5.42e-14,  4.44e-14,  1.74e-13, -1.33e-14,  8.04e-14,  4.44e-14,  3.42e-14,  1.69e-13,  6.66e-14,
       -5.91e-14,  1.33e-14, -1.15e-14, -3.91e-14,  4.88e-14,  9.77e-15, -3.55e-14, -4.71e-14, -1.13e-13,  3.64e-14,
        2.49e-14,  7.15e-14,  3.55e-15,  7.11e-15, -8.35e-14,  1.31e-13, -4.09e-14,  1.90e-13,  1.09e-13, -5.77e-14,
       -1.04e-13,  1.06e-13, -7.64e-14,  6.13e-14,  5.20e-14, -6.97e-14,  3.64e-14,  2.66e-15,  1.07e-13, -4.00e-14,
        8.70e-14,  3.55e-14,  1.29e-13, -1.04e-13,  1.33e-15, -7

In [26]:
res.x

Array([ 0.4 ,  0.2 ,  0.07,  0.86,  0.1 ,  0.75,  0.28,  0.61,  0.85,  0.61,  0.8 ,  0.63,  0.99,  0.73,  0.44,  0.82,
        0.67,  0.67,  0.78,  0.55,  0.27,  0.87,  0.53,  0.52, -0.03,  0.87,  0.85,  0.39,  0.98,  0.84,  0.65,  0.05,
        0.32,  0.36,  0.37,  0.46,  0.78,  0.76,  0.97,  0.87,  0.21,  0.86,  0.6 ,  0.43,  0.87,  0.13,  0.55,  0.58,
        0.94, -0.01,  0.38,  0.73,  0.8 ,  0.68,  0.57,  0.65,  0.31,  0.78,  0.35,  0.37,  0.28,  0.3 ,  0.61,  0.6 ,
        0.55,  0.52,  0.63,  0.39,  0.58,  0.83,  0.23,  0.79,  0.77,  0.58,  0.56,  0.24,  0.66,  0.93,  0.96,  0.94,
        0.42,  0.44,  0.09,  0.64,  0.73,  0.23,  0.36,  0.9 ,  0.39,  0.38,  0.43,  0.63,  0.97,  0.86,  0.31,  0.15,
        0.71,  0.11,  0.56,  0.85], dtype=float64)

In [38]:
res.x

Array([ 0.4 ,  0.2 ,  0.07,  0.86,  0.1 ,  0.75,  0.28,  0.61,  0.85,  0.61,  0.8 ,  0.63,  0.99,  0.73,  0.44,  0.82,
        0.67,  0.67,  0.78,  0.55,  0.27,  0.87,  0.53,  0.52, -0.03,  0.87,  0.85,  0.39,  0.98,  0.84,  0.65,  0.05,
        0.32,  0.36,  0.37,  0.46,  0.78,  0.76,  0.97,  0.87,  0.21,  0.86,  0.6 ,  0.43,  0.87,  0.13,  0.55,  0.58,
        0.94, -0.01,  0.38,  0.73,  0.8 ,  0.68,  0.57,  0.65,  0.31,  0.78,  0.35,  0.37,  0.28,  0.3 ,  0.61,  0.6 ,
        0.55,  0.52,  0.63,  0.39,  0.58,  0.83,  0.23,  0.79,  0.77,  0.58,  0.56,  0.24,  0.66,  0.93,  0.96,  0.94,
        0.42,  0.44,  0.09,  0.64,  0.73,  0.23,  0.36,  0.9 ,  0.39,  0.38,  0.43,  0.63,  0.97,  0.86,  0.31,  0.15,
        0.71,  0.11,  0.56,  0.85], dtype=float64)